# SwiftLint configuration file

# Paths to ignore during linting
excluded:
  - .git
  - Pods
  - fastlane
  - builds
  - DerivedData
  - Generated
  - '**/*.generated.swift'

# Default rules are enabled unless explicitly disabled
disabled_rules:
  # Explicit disables with reasons
  - force_cast                    # Sometimes needed for UI development
  - force_try                     # Sometimes needed for testing
  - identifier_name               # Custom naming may be required
  - large_tuple                   # Complex return types might be needed
  - trailing_whitespace           # IDE handles this
  - weak_delegate                 # Not always necessary
  - function_body_length          # Complex functions might be required
  - implicit_return              # Explicit returns can be clearer
  - todo                         # Allow TODOs in development

# Opt-in rules
opt_in_rules:
  # Code Structure
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - explicit_init
  - implicit_return
  - let_var_whitespace
  - multiline_arguments
  - multiline_parameters
  - operator_usage_whitespace
  - prefer_zero_over_explicit_init
  - redundant_type_annotation
  
  # Style
  - attributes
  - file_name_no_space
  - literal_expression_end_indentation
  - multiline_literal_brackets
  - sorted_imports
  - unneeded_parentheses_in_closure_argument
  
  # Performance
  - empty_collection_literal
  - empty_count
  - first_where
  - last_where
  - contains_over_filter_count
  - contains_over_filter_is_empty
  - empty_string
  
  # Safety
  - discouraged_optional_boolean
  - fatal_error_message
  - toggle_bool
  - unowned_variable_capture
  - untyped_error_in_catch
  
  # Testing
  - empty_xctest_method
  
  # Documentation
  - missing_docs
  
  # Architecture
  - extension_access_modifier
  - strict_fileprivate
  - private_outlet
  - private_action

# Customized rule configurations
line_length:
  warning: 120
  error: 200
  ignores_comments: true
  ignores_urls: true

file_length:
  warning: 400
  error: 1000

type_name:
  min_length: 3
  max_length: 
    warning: 40
    error: 50

identifier_name:
  min_length: 
    warning: 2
    error: 1
  max_length: 
    warning: 40
    error: 60
  excluded:
    - id
    - URL
    - x
    - y

function_parameter_count:
  warning: 6
  error: 8

nesting:
  type_level:
    warning: 3
  statement_level:
    warning: 5

cyclomatic_complexity:
  warning: 15
  error: 25

type_body_length:
  warning: 300
  error: 500

function_body_length:
  warning: 50
  error: 100

vertical_whitespace:
  max_empty_lines: 2

trailing_comma:
  mandatory_comma: true

# Custom rules configurations
custom_rules:
  no_direct_standard_out_logs:
    name: "No Direct Print Logs"
    regex: "print\\("
    message: "Use a logging framework instead of print"
    severity: warning
